package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"backend/graphql/generated"
	"backend/graphql/model"
	"context"
	"fmt"

	"github.com/edufilhocruz/neurocloser/backend/models"
)

// CnpjFormatado is the resolver for the cnpjFormatado field.
func (r *estabelecimentoResolver) CnpjFormatado(ctx context.Context, obj *models.Estabelecimento) (string, error) {
	panic(fmt.Errorf("not implemented: CnpjFormatado - cnpjFormatado"))
}

// Empresas is the resolver for the empresas field.
func (r *queryResolver) Empresas(ctx context.Context, limit *int, offset *int) ([]*models.Empresa, error) {
	panic(fmt.Errorf("not implemented: Empresas - empresas"))
}

// Empresa is the resolver for the empresa field.
func (r *queryResolver) Empresa(ctx context.Context, cnpjBasico string) (*models.Empresa, error) {
	panic(fmt.Errorf("not implemented: Empresa - empresa"))
}

// Estabelecimento is the resolver for the estabelecimento field.
func (r *queryResolver) Estabelecimento(ctx context.Context, id int) (*models.Estabelecimento, error) {
	panic(fmt.Errorf("not implemented: Estabelecimento - estabelecimento"))
}

// SociosByCnpjBasico is the resolver for the sociosByCnpjBasico field.
func (r *queryResolver) SociosByCnpjBasico(ctx context.Context, cnpjBasico string) ([]*models.Socio, error) {
	panic(fmt.Errorf("not implemented: SociosByCnpjBasico - sociosByCnpjBasico"))
}

// CnaeByCodigo is the resolver for the cnaeByCodigo field.
func (r *queryResolver) CnaeByCodigo(ctx context.Context, codigo string) (*models.CNAE, error) {
	panic(fmt.Errorf("not implemented: CnaeByCodigo - cnaeByCodigo"))
}

// BuscarProspeccao is the resolver for the buscarProspeccao field.
func (r *queryResolver) BuscarProspeccao(ctx context.Context, filter *model.ProspeccaoFilter, limit *int, offset *int) ([]*models.ProspeccaoDetalhada, error) {
	panic(fmt.Errorf("not implemented: BuscarProspeccao - buscarProspeccao"))
}

// Estabelecimento returns generated.EstabelecimentoResolver implementation.
func (r *Resolver) Estabelecimento() generated.EstabelecimentoResolver {
	return &estabelecimentoResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type estabelecimentoResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
