// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ProspeccaoFilter struct {
	Cnpj                 *string  `json:"cnpj,omitempty"`
	RazaoSocial          *string  `json:"razaoSocial,omitempty"`
	NomeFantasia         *string  `json:"nomeFantasia,omitempty"`
	Uf                   *string  `json:"uf,omitempty"`
	SituacaoCadastral    *string  `json:"situacaoCadastral,omitempty"`
	PorteEmpresa         *string  `json:"porteEmpresa,omitempty"`
	CnaeFiscal           *string  `json:"cnaeFiscal,omitempty"`
	CnaeFiscalSecundaria *string  `json:"cnaeFiscalSecundaria,omitempty"`
	MinCapitalSocial     *float64 `json:"minCapitalSocial,omitempty"`
	MaxCapitalSocial     *float64 `json:"maxCapitalSocial,omitempty"`
}

type Query struct {
}
